// Generated by LiveScript 1.5.0
(function(){
  var React, ref$, AppRegistry, Text, StyleSheet, View, styles, studio_mobile, proto2base64, builder, proto, stringifyEnums, decode_proto, encode_proto, jf, jQuery, bullet;
  React = require("react");
  ref$ = require("react-native"), AppRegistry = ref$.AppRegistry, Text = ref$.Text, StyleSheet = ref$.StyleSheet, View = ref$.View;
  styles = StyleSheet.create({
    container: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#F5FCFF'
    },
    welcome: {
      fontSize: 20,
      textAlign: 'center',
      margin: 10
    },
    instructions: {
      textAlign: 'center',
      color: '#333333',
      marginBottom: 5
    }
  });
  studio_mobile = (function(superclass){
    var prototype = extend$((import$(studio_mobile, superclass).displayName = 'studio_mobile', studio_mobile), superclass).prototype, constructor = studio_mobile;
    studio_mobile.prototype.render = function(){
      return React.createElement(View, {
        style: styles.container
      }, [
        React.createElement(Text, {
          style: styles.welcome,
          key: "title"
        }, "Welcome to React Native!!!"), React.createElement(Text, {
          style: styles.instructions,
          key: "help"
        }, "To get started, edit index.ios.js"), React.createElement(Text, {
          style: styles.instructions,
          key: "instr"
        }, "Press Cmd+R to reload,\nCmd+D or shake for dev menu")
      ]);
    };
    function studio_mobile(){
      studio_mobile.superclass.apply(this, arguments);
    }
    return studio_mobile;
  }(React.Component));
  AppRegistry.registerComponent('studio_mobile', function(){
    return studio_mobile;
  });
  proto2base64 = require('base64-arraybuffer');
  builder = require("protobufjs").loadProto(require("./app/sproto"), {
    file: "studio.proto",
    root: "a"
  });
  proto = builder.build().lemooor.studio;
  stringifyEnums = function(message){
    if (message && message.$type && message.$type.children) {
      message.$type.children.forEach(function(child){
        var field, dict;
        field = child.name;
        if (message[field] && child.element.resolvedType) {
          switch (child.element.resolvedType.className) {
          case 'Enum':
            dict = child.element.resolvedType.children.reduce(function(acc, arg$){
              var id, name;
              id = arg$.id, name = arg$.name;
              acc[id] = name;
              return acc;
            }, {});
            if (child.repeated) {
              return message[field] = message[field].map(function(el){
                if (dict[el]) {
                  return dict[el];
                } else {
                  return el;
                }
              });
            } else {
              if (dict[message[field]]) {
                return message[field] = dict[message[field]];
              }
            }
            break;
          case 'Message':
            if (child.repeated) {
              return message[field] = message[field].map(function(el){
                return stringifyEnums(el);
              });
            } else {
              return message[field] = stringifyEnums(message[field]);
            }
          }
        }
      });
    }
    return message;
  };
  decode_proto = function(data){
    var error;
    try {
      return stringifyEnums(proto.Response.decode64(data.data));
    } catch (e$) {
      error = e$;
      return "protobuf decode error " + error + " raw data : " + data;
    }
  };
  encode_proto = function(data){
    return proto2base64.encode(proto.Request.encode(data).toArrayBuffer());
  };
  jf = require("jsfunky");
  jQuery = {
    ajax: require("component-ajax")
  };
  jQuery.extend = function(some){
    return jf.merge(jQuery, some);
  };
  global.jQuery = jQuery;
  require("bulletjs");
  bullet = jQuery.bullet("ws://127.0.0.1:7773/bullet");
  bullet.onopen = function(){
    return console.log("соединение с сервером установлено");
  };
  bullet.ondisconnect = function(){
    return console.log("соединение с сервером потеряно");
  };
  bullet.onclose = function(){
    return console.log("соединение с сервером закрыто");
  };
  bullet.onheartbeat = function(){
    return console.log("tick ...");
  };
  bullet.onmessage = function(data){
    return console.log(decode_proto(data));
  };
  function extend$(sub, sup){
    function fun(){} fun.prototype = (sub.superclass = sup).prototype;
    (sub.prototype = new fun).constructor = sub;
    if (typeof sup.extended == 'function') sup.extended(sub);
    return sub;
  }
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
